name: ci
on: [push, pull_request, release]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19'
    - run: go install github.com/mattn/goveralls@latest
    - run: |
        make test
        make
        make build.docker
    - run: goveralls -coverprofile=profile.cov -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the latest Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        VERSION=latest make build.push
      if: github.ref == 'refs/heads/master'
    - name: Push the release Docker image
      run: |
        echo "$GITHUB_REF_NAME"
        VERSION=$GITHUB_REF_NAME make build.push
      if: github.event_name == 'release'
